#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

mkdir -p logs/ltsf_by_model logs/mvpf_plus_by_dataset logs/ltsf_efficiency results

export ADAWARP_ALLOCATION="${ADAWARP_ALLOCATION:-IRI23021}"
export ADAWARP_PARTITION="${ADAWARP_PARTITION:-gh}"
export ADAWARP_WALLTIME="${ADAWARP_WALLTIME:-24:00:00}"
export ADAWARP_LTSF_DATASETS="${ADAWARP_LTSF_DATASETS:-ETTm1 ETTm2}"
export ADAWARP_LTSF_HORIZONS="${ADAWARP_LTSF_HORIZONS:-96 192 336 720}"
export ADAWARP_LTSF_SEEDS="${ADAWARP_LTSF_SEEDS:-42}"

export ADAWARP_TSLIB_EPOCHS="${ADAWARP_TSLIB_EPOCHS:-10}"
export ADAWARP_TSLIB_BATCH_SIZE="${ADAWARP_TSLIB_BATCH_SIZE:-32}"
export ADAWARP_TSLIB_LR="${ADAWARP_TSLIB_LR:-0.0001}"
export ADAWARP_TSLIB_D_MODEL="${ADAWARP_TSLIB_D_MODEL:-128}"
export ADAWARP_TSLIB_D_FF="${ADAWARP_TSLIB_D_FF:-256}"
export ADAWARP_TSLIB_N_HEADS="${ADAWARP_TSLIB_N_HEADS:-8}"
export ADAWARP_TSLIB_E_LAYERS="${ADAWARP_TSLIB_E_LAYERS:-2}"
export ADAWARP_TSLIB_D_LAYERS="${ADAWARP_TSLIB_D_LAYERS:-1}"
export ADAWARP_TSLIB_PATIENCE="${ADAWARP_TSLIB_PATIENCE:-3}"

export ADAWARP_CUSTOM_LTSF_EPOCHS="${ADAWARP_CUSTOM_LTSF_EPOCHS:-10}"
export ADAWARP_CUSTOM_LTSF_BATCH_SIZE="${ADAWARP_CUSTOM_LTSF_BATCH_SIZE:-16}"
export ADAWARP_CUSTOM_LTSF_EVAL_BATCH_SIZE="${ADAWARP_CUSTOM_LTSF_EVAL_BATCH_SIZE:-16}"
export ADAWARP_CUSTOM_LTSF_LR="${ADAWARP_CUSTOM_LTSF_LR:-0.001}"
export ADAWARP_CUSTOM_LTSF_WEIGHT_DECAY="${ADAWARP_CUSTOM_LTSF_WEIGHT_DECAY:-0.0001}"
export ADAWARP_CUSTOM_LTSF_D_MODEL="${ADAWARP_CUSTOM_LTSF_D_MODEL:-256}"
export ADAWARP_CUSTOM_LTSF_DEPTH="${ADAWARP_CUSTOM_LTSF_DEPTH:-2}"
export ADAWARP_CUSTOM_LTSF_BLOCKS="${ADAWARP_CUSTOM_LTSF_BLOCKS:-4}"
export ADAWARP_CUSTOM_LTSF_DROPOUT="${ADAWARP_CUSTOM_LTSF_DROPOUT:-0.05}"
export ADAWARP_VPNET_PATCH_LEN="${ADAWARP_VPNET_PATCH_LEN:-16}"

export ADAWARP_MVPF_PLUS_EPOCHS="${ADAWARP_MVPF_PLUS_EPOCHS:-10}"
export ADAWARP_MVPF_PLUS_BATCH_SIZE="${ADAWARP_MVPF_PLUS_BATCH_SIZE:-16}"
export ADAWARP_MVPF_PLUS_EVAL_BATCH_SIZE="${ADAWARP_MVPF_PLUS_EVAL_BATCH_SIZE:-16}"
export ADAWARP_MVPF_PLUS_LR="${ADAWARP_MVPF_PLUS_LR:-0.0007}"
export ADAWARP_MVPF_PLUS_WEIGHT_DECAY="${ADAWARP_MVPF_PLUS_WEIGHT_DECAY:-0.0001}"
export ADAWARP_MVPF_PLUS_D_MODEL="${ADAWARP_MVPF_PLUS_D_MODEL:-128}"
export ADAWARP_MVPF_PLUS_DEPTH="${ADAWARP_MVPF_PLUS_DEPTH:-2}"
export ADAWARP_MVPF_PLUS_DROPOUT="${ADAWARP_MVPF_PLUS_DROPOUT:-0.05}"
export ADAWARP_MVPF_PLUS_PATCH_LENS="${ADAWARP_MVPF_PLUS_PATCH_LENS:-8 16 32}"
export ADAWARP_MVPF_PLUS_NUM_PROTOTYPES="${ADAWARP_MVPF_PLUS_NUM_PROTOTYPES:-8}"
export ADAWARP_MVPF_PLUS_MAX_SHIFT="${ADAWARP_MVPF_PLUS_MAX_SHIFT:-2}"
export ADAWARP_MVPF_PLUS_RECONSTRUCTION_WEIGHT="${ADAWARP_MVPF_PLUS_RECONSTRUCTION_WEIGHT:-0.03}"
export ADAWARP_MVPF_PLUS_PATIENCE="${ADAWARP_MVPF_PLUS_PATIENCE:-0}"

export ADAWARP_LTSF_SEQ_LEN="${ADAWARP_LTSF_SEQ_LEN:-96}"
export ADAWARP_LTSF_MAX_TRAIN_WINDOWS="${ADAWARP_LTSF_MAX_TRAIN_WINDOWS:-2048}"
export ADAWARP_LTSF_MAX_VAL_WINDOWS="${ADAWARP_LTSF_MAX_VAL_WINDOWS:-1024}"
export ADAWARP_LTSF_MAX_EVAL_WINDOWS="${ADAWARP_LTSF_MAX_EVAL_WINDOWS:-2048}"

BASELINE_PARENT="${ADAWARP_ETTM_BASELINE_PARENT:-$WORK/motion_code-master/results/vista_ltsf_ettm_paper_baselines}"
MVPF_PARENT="${ADAWARP_ETTM_MVPF_PARENT:-$WORK/motion_code-master/results/vista_ltsf_ettm_paper_adawarp_mvpf}"
EFF_ROOT="${ADAWARP_EFFICIENCY_OUTPUT_ROOT:-$WORK/motion_code-master/results/vista_ltsf_ettm2_efficiency}"

if [[ "${ADAWARP_SUBMIT_BASELINES:-1}" == "1" ]]; then
  export ADAWARP_LTSF_MODELS_TO_SUBMIT="${ADAWARP_LTSF_MODELS_TO_SUBMIT:-DLinear PatchTST TimesNet iTransformer TimeMixer FEDformer VPNet}"
  export ADAWARP_LTSF_JOB_PARENT="$BASELINE_PARENT"
  echo "[submit_ltsf_ettm_paper_models] submitting baselines: $ADAWARP_LTSF_MODELS_TO_SUBMIT"
  bash scripts/tacc/submit_ltsf_by_model.sh
fi

if [[ "${ADAWARP_SUBMIT_MVPF:-1}" == "1" ]]; then
  export ADAWARP_MVPF_PLUS_DATASETS_TO_SUBMIT="${ADAWARP_MVPF_PLUS_DATASETS_TO_SUBMIT:-$ADAWARP_LTSF_DATASETS}"
  export ADAWARP_MVPF_PLUS_JOB_PARENT="$MVPF_PARENT"
  echo "[submit_ltsf_ettm_paper_models] submitting AdaWarp-MVPF datasets: $ADAWARP_MVPF_PLUS_DATASETS_TO_SUBMIT"
  bash scripts/tacc/submit_adawarp_mvpf_plus_by_dataset.sh
fi

if [[ "${ADAWARP_SUBMIT_ETTM2_EFFICIENCY:-1}" == "1" ]]; then
  echo "[submit_ltsf_ettm_paper_models] submitting ETTm2 efficiency profiler"
  sbatch \
    -A "$ADAWARP_ALLOCATION" \
    -p "$ADAWARP_PARTITION" \
    -t "${ADAWARP_EFFICIENCY_WALLTIME:-02:00:00}" \
    -J "${ADAWARP_EFFICIENCY_JOB_NAME:-ltsf_ettm2_eff}" \
    slurm/ltsf_ettm2_efficiency_vista.sbatch "$EFF_ROOT"
fi

echo "[submit_ltsf_ettm_paper_models] done"
